name: Daily Lightning Data Scrape

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write access to repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use default GITHUB_TOKEN for checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run scrape script
        run: python lightning_scrape.py

      - name: Commit and push if there are changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add lightning_data.json
          git commit -m "Update lightning data - $(date -u)" || echo "No changes to commit"
          git push
